options:
  source:
    type: string
    default:
    description: |
      Repository from which to install LXD.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported release pocket
  trust-password:
    type: string
    default: password
    description: Password to set for the LXD server.
  block-device:
    type: string
    default:
    description: |
       Device to be used to back LXD storage. May be an valid block
       device or a path and size to a local file (/path/to/file.img|$sizeG),
       which will be created and used as a loopback device (for testing only).
       .
       This will be use to store lxd containers.
  fs-type:
    type: string
    default: btrfs
    description: |
       Default filesystem type: btrfs or lvm
  use-source:
    type: boolean
    default: False
    description: Use LXD source from github.

