options:
  source:
    type: string
    default:
    description: |
      Repository from which to install LXD.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported release pocket
  block-devices:
    type: string
    default:
    description: |
       A space-separated list of devices to use to back the LXD storage. Items
       in this list should ideally be valid block device paths, but entries
       that are not found will be ignored.

       For now only the first block device in the list will be considered.
  loopback-device:
    type: string
    default:
    decription: |
       FOR TESTING ONLY - The path and size to a to a local file
       (/path/to/file.img|$sizeG), which will be created and used as a
       loopback device.
       I/O is, as expected, very slow when using this.

       Setting this to anything will override whatever is passed in
       block-devices.
  overwrite:
    default: False
    type: boolean
    description: |
      If enabled, the charm will attempt to overwrite block devices
      containing previous filesystems or LVM, assuming it is not in use.
  storage-type:
    type: string
    default: btrfs
    description: |
       LXD container storage type: btrfs or lvm
  ephemeral-unmount:
    type: string
    default:
    description: |
      Cloud instances provide ephemeral storage which is normally mounted
      on /mnt.
      .
      Providing this option will force an unmount of the ephemeral device
      so that it can be used for LXD container storage.  This is useful for
      testing purposes (cloud deployment is not a typical use case).
  use-source:
    type: boolean
    default: False
    description: Use LXD source from github.

