options:
  lxd-origin:
    type: string
    default: "distro"
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported release pocket
  lxd-trust-password:
    type: string
    default: password
    description: Password to set for the LXD server.
  lxd-use-source:
    type: boolean
    default: False
    description: Use LXD source from github.
  lxd-block-device:
    type: string
    default: /mnt/disk.img|20G
    description: |
       Deivce to be used to back LXD storage. May be an valid block
       device or a path and size to a local file (/path/to/file.img|$sizeG),
       which will be created and used as a loopback device (for testing only).
       Multiple devices may not be specified as a space-seperated list of
       devices.
       If set to "guess", the charm will attempt to format and mount all extra
       block devices (this is currently experimentall and potentially
       danagerous).
       .
       This will be use to store the lxd containers instance
  lxd-fs-type:
    type: string
    default: btrfs
    description: |
       Default filesystem type: btrfs or lvm
